[project]
name = 'StableAmp'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.mock-usda-token]
path = 'contracts/mock-usda-token.clar'
clarity_version = 3
epoch = 3.1

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 3.1

[contracts.stableamp]
path = 'contracts/stableamp.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
